site: Opal Blue Langton
url: https://opalbluelangton.com 
author:
  name: Opal Blue Langton
  email: 
  url: 
  avatar: 
title: Opal Blue Langton
description:
logo: 
image: 
twitter:
  username:
  creator:
  card:
social:
  name:
  links:
    - https://twitter.com/#
    - https://www.dribbble.com/#
    - https://github.com/#
    - https://codepen.io/#
  
permalink: pretty

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
